In [ ]:
!git clone https://github.com/skwang89/workspace.git

fatal: destination path 'workspace' already exists and is not an empty directory.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [ ]:
# first.py

import tensorflow as tf
# 상수 선언
hello = tf.constant('Hello, TensorFlow!')

print(hello)
# tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)

# numpy() 메소드를 사용하여 텐서의 값을 numpy데이터 타입으로 변환하여 출력
print(hello.numpy())

# decode('utf-8')메소드로 bytes 클래스를 str 클래스로 변환
# 문자열 앞에 보이던 b가 사라짐
print(hello.numpy().decode('utf-8'))
# Hello, TensorFlow!

tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)
b'Hello, TensorFlow!'
Hello, TensorFlow!


In [ ]:
# korean.py

# 상수 선언: 한글
hi = tf.constant('안녕')

# 텐서 값으로 한글을 사용한 경우
print(hi)
# tf.Tensor(b'\xec\x95\x88\xeb\x85\x95', shape=(), dtype=string)

print(hi.numpy())
# b'\xec\x95\x88\xeb\x85\x95'

# decode('utf-8') 메소드로 bytes 클래스를 str 클래스로 변환 *decode('utf8')도 가능
print(hi.numpy().decode('utf8'))
# 안녕

tf.Tensor(b'\xec\x95\x88\xeb\x85\x95', shape=(), dtype=string)
b'\xec\x95\x88\xeb\x85\x95'
안녕


In [ ]:
# constant_operation01.py

import tensorflow as tf

# 상수 정의
a = tf.constant(2)
b = tf.constant(3)

c = a+b

# 연산 결과 출력
print(a.numpy())
print(b.numpy())
print(c.numpy())
print(a.numpy()+b.numpy())
# 2
# 3
# 5
# 5

2
3
5
5


In [ ]:
# constant_operation02.py

import tensorflow as tf

# 상수 정의
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

# 연산 정의
cal1 = a + b * c
cal2 = (a + b) * c

# 연산 결과 출력
print(cal1.numpy())
print(cal2.numpy())
# 14
# 20

14
20


In [ ]:
# constant_operation03.py
import tensorflow as tf
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)

# 연산
node3 = tf.add(node1, node2)
node4 = tf.multiply(node1, node2)

# 연산 결과 출력
print(node1.numpy())
print(node2.numpy())
print(node3.numpy())
print(node4.numpy())
# 3.0
# 4.0
# 7.0
# 12.0

3.0
4.0
7.0
12.0


In [ ]:
# constant_operation04.py

import tensorflow as tf

# 상수 선언
x1 = tf.constant([1, 2, 3, 4])
x2 = tf.constant([5, 6, 7, 8])

# 연산
cal1 = tf.add(x1, x2) # 더하기
cal2 = tf.subtract(x1, x2) # 빼기
cal3 = tf.multiply(x1, x2) # 곱하기
cal4 = tf.divide(x1, x2) # 나누기

# 연산 결과 출력
print(cal1.numpy())
print(cal2.numpy())
print(cal3.numpy())
print(cal4.numpy())

In [36]:
# variable01.py

import tensorflow as tf

# 변수 선언
v1 = tf.Variable(50)    # v1 변수의 초기값 50

# 변수 출력
print('v1=',v1)
print('v1=',v1.numpy())
# v1= <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=50>
# v1= 50

v1= <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=50>
v1= 50


In [49]:
# variable02.py

import tensorflow as tf

# 변수 선언
v1 = tf.Variable(50)          # v1 변수의 초기값 50
v2 = tf.Variable([1,2,3])     # rank: 1, shape: (3)
v3 = tf.Variable([[1],[2]])   # rand: 2, shape: (2,1)

# 변수 출력
print('v1=',v1.numpy())
print('v2=',v2.numpy())
print('v3=',v3.numpy())
# v1= 50
# v2= [1 2 3]
# v3= [[1]
  [2]]

(2, 1)
v1= 50
v2= [1 2 3]
v3= [[1]
 [2]]


In [47]:
# variable03.py

import tensorflow as tf

# 변수 선언
x = tf.Variable([[2, 2, 2],[2, 2, 2]]) # rank: 2, shape(2,3) 2행 3열
y = tf.Variable([[3, 3, 3],[3, 3, 3]]) # rank: 2, shape(2,3) 2행 3열

# 연산
z1 = tf.add(x, y)                   # 덧셈
z2 = tf.subtract(x, y)              # 뺄셈
z3 = tf.multiply(x, y)              # 곱셈
z4 = tf.matmul(x, tf.transpose(y))  # matrix 곱셈 (tf.transpose() : 젂치행렬)
z5 = tf.pow(x, 3)                   # 3제곱

# shape 구하기
print(x.get_shape()) # (2, 3)
print(y.get_shape()) # (2, 3)

# 연산 결과 출력
print(z1.numpy())
print(z2.numpy())
print(z3.numpy())
print(z4.numpy())
print(z5.numpy())

(2, 3)
(2, 3)
[[5 5 5]
 [5 5 5]]
[[-1 -1 -1]
 [-1 -1 -1]]
[[6 6 6]
 [6 6 6]]
[[18 18]
 [18 18]]
[[8 8 8]
 [8 8 8]]


In [48]:
# matrix.py

import tensorflow as tf

x = tf.Variable([[3., 3.]]) # shape: (1, 2) 1행 2열
y = tf.Variable([[2.],[2.]]) # shape: (2, 1) 2행 1열

mat = tf.matmul(x, y) # matrix 곱셈

# shape 구하기
print(x.get_shape()) # shape: (1, 2) 1행 2열
print(y.get_shape()) # shape: (2, 1) 2행 1열

# 연산 결과 출력
print(x.numpy())
print(y.numpy())
print(mat.numpy())

(1, 2)
(2, 1)
[[3. 3.]]
[[2.]
 [2.]]
[[12.]]


In [51]:
# variable04.py

import tensorflow as tf

# 변수 선언
v1 = tf.Variable(tf.zeros([2,3]))               # [[ 0. 0. 0.] [ 0. 0. 0.]]
v2 = tf.Variable(tf.ones([2,3], tf.int32))      # [[1 1 1] [1 1 1]]
v3 = tf.Variable(tf.zeros_like(tf.ones([2,3]))) # [[ 0. 0. 0.] [ 0. 0. 0.]]
v4 = tf.Variable(tf.fill([2,3], 2))             # [[2 2 2] [2 2 2]]
v5 = tf.Variable(tf.fill([2,3], 2.0))           # [[ 2. 2. 2.] [ 2. 2. 2.]]

# 변수 출력
print(v1.numpy())
print(v2.numpy())
print(v3.numpy())
print(v4.numpy())
print(v5.numpy())

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[2 2 2]
 [2 2 2]]
[[2. 2. 2.]
 [2. 2. 2.]]


In [66]:
# random01.py

import tensorflow as tf

# 난수 생성
a = tf.random.uniform([1], 0, 1) # 0 ~ 1 사이의 난수 1개 발생
b = tf.random.uniform([1], 0, 10) # 0 ~ 10 사이의 난수 1개 발생
print(a.numpy())
print(b.numpy())
""" 난수 생성 """
# 정규분포 난수 : 평균: -1, 표준편차: 4
norm = tf.random.normal([2,3], mean= -1, stddev= 4)
print(norm.numpy())

# 주어진 값들을 shuffle() 함수로 무작위로 섞음
c = tf.constant([[1,2,],[3,4,],[5,6]])
shuff = tf.random.shuffle(c)
print(shuff.numpy())

# 균등 분포 난수: 0 ~ 3 값 사이의 2행 3열 난수 발생
unif = tf.random.uniform([2,3], minval= -1, maxval= 3)
print(unif.numpy())


[0.19306886]
[8.104811]
[[ 2.9401546  1.8788874  1.474781 ]
 [-0.4788403  2.9047475 -6.265603 ]]
[[3 4]
 [1 2]
 [5 6]]
[[ 1.9175162   0.52560854 -0.9351649 ]
 [ 1.073329    2.0233078  -0.23329067]]


In [ ]:
# Rank: 텐서의 차원은 rank로 나타낸다.
# Shape: 텐서의 행과 열이 몇 개인지를 나타낸다.
# Type: 텐서의 데이터가 어떤 형식인지를 나타낸다.